# Generated by Django 3.2.8 on 2021-10-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sur_Name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('Firste_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('Last_name', models.CharField(max_length=30, verbose_name='Отчество')),
                ('Adress', models.CharField(max_length=250, verbose_name='Адрес')),
                ('Day', models.CharField(max_length=20, verbose_name='День желаемой доставки')),
                ('Cridet_card', models.CharField(max_length=20, verbose_name='Кредитная карта')),
                ('Product', models.CharField(max_length=20, verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
